### ISSUE TITLE
Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by babakfp** [dalirnet/rtl-markdown#11]

**Comment by dalirnet** [comment]
Hey @babakfp 
I need more info to track it down:

- Steps to reproduce
- Error messages or logs
- Your environment (OS, Node.js version, etc.)

Thanks

**Comment by MelalDev** [comment]
Hi, I have the same issue,

Steps to reproduce : 
OS : Windows 10 22h2 
VS Code  1.96.2 ( Latest version ) completely fresh ,
It run on administrator privilege on first step : Active RTL-Markdown , VS Code prompt with following error : 

![image](https://github.com/user-attachments/assets/229309b3-ff7a-4b37-9c46-51be5102d8c0)

Here is the log of the extension : 
2024-12-31 22:49:33.453 [error] TypeError: Cannot read properties of undefined (reading 'path')
	at get original (c:\Users\MyUserName\.vscode\extensions\dalirnet.rtl-markdown-0.0.10\script\extension.js:12:46)
	at Object.status (c:\Users\MyUserName\.vscode\extensions\dalirnet.rtl-markdown-0.0.10\script\extension.js:31:48)
	at deactive (c:\Users\MyUserName\.vscode\extensions\dalirnet.rtl-markdown-0.0.10\script\extension.js:99:19)
	at c:\Users\MyUserName\.vscode\extensions\dalirnet.rtl-markdown-0.0.10\script\extension.js:155:76
	at cw.h (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32833)
	at cw.$executeContributedCommand (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:33683)
	at Dy.S (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
	at Dy.Q (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
	at Dy.M (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
	at Dy.L (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113249)
	at kh.value (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
	at P.B (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at Vn.fire (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
	at kh.value (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
	at P.B (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at Vn.fire (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
	at MessagePortMain.<anonymous> (file:///c:/Users/MyUserName/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
	at MessagePortMain.emit (node:events:518:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) rtl-markdown.deactive {"value":"dalirnet.rtl-markdown","_lower":"dalirnet.rtl-markdown"}

**Comment by dalirnet** [comment]
https://github.com/electron/electron/issues/40501
